#
#
#
directory_format = <tr><td><a class="dir" href="$LINK">$DIR_NAME</a> $NEW<td><td>$SONG_COUNT</td><td>$DIR_COUNT</td><td>[$RECURSE]</td></tr>

#
song_format = $ARTIST - $ALBUM - $SONGNAME - ( $LENGTH )


#file_format = <tr><td width="10%">&nbsp;</td><td><a href="$LINK">$SONG_FORMAT</a></td></tr>

file_format = <tr><td><a href="$LINK">$SONG_FORMAT</a></td></tr>