##
#
#  This next option controls how directories are displayed on the index
# pages.
#
#  There are several defined variables which you can choose to use:
#
#  $LINK       = The actual URL of the directory.
#
#  $DIR_NAME   = The name of the directory.
#
#  $SONG_COUNT = The number of songs contained in the directory.
#
#  $DIR_COUNT  = The number of subdirectories in the directory.
#
#  $RECURSE    = A link to play the contents of the directory recurisvely.
#
#
directory_format  = <tr class="rowstyle1"><td width="5%">&nbsp;</td><td class="linktext1">[<a href="$LINK">$DIR_NAME</a>] $NEW</td><td align="right" class="linktext">$SONG_COUNT</td><td align="right" class="linktext">$DIR_COUNT</td><td align="center" class="linktext">[$RECURSE]</td></tr>
directory_format2 = <tr class="rowstyle2"><td width="5%">&nbsp;</td><td class="linktext2">[<a href="$LINK">$DIR_NAME</a>] $NEW</td><td align="right" class="linktext">$SONG_COUNT</td><td align="right" class="linktext">$DIR_COUNT</td><td align="center" class="linktext">[$RECURSE]</td></tr>




##
# File format
##
#
#   This option is analogous to the 'directory_format' option above.
#
#   It specifies how the files should be listed.
#
#   $LINK         Is the link to the track itself
#
#   $SONG_FORMAT  Is a template string which is described below.
#
#
file_format  = <tr class="rowstyle1"><td width="5%">&nbsp;</td><td width="71%" class="linktext">.:: <a href="$LINK">$SONG_FORMAT</a></td><td class="linktext"></td><td align="center" class="linktext" >[<a href="/info$PLAINLINK">Info</a>] [<a href="$LINK">Play</a>] [<a href="$PLAINLINK">Download</a>]</td></tr>
file_format2 = <tr class="rowstyle2"><td width="5%">&nbsp;</td><td width="71%" class="linktext">.:: <a href="$LINK">$SONG_FORMAT</a></td><td class="linktext"></td><td align="center" class="linktext" >[<a href="/info$PLAINLINK">Info</a>] [<a href="$LINK">Play</a>] [<a href="$PLAINLINK">Download</a>]</td></tr>

##
#
#  This next setting, `song_format', allows you to configure how the
# MP3 and OGG Vorbis files are displayed.
#
#  If the file which has been found contains any tag information then
# the following values will be available to you:
#
#   $ARTIST   -> The artist of the song.
#
#   $ALBUM    -> The album the song came from.
#
#   $COMMENT  -> The comment string attatched to the song, if any.
#                NOT AVAILABLE FOR OGG FILES.
#
#   $SONGNAME -> The name of the song.
#
#   $YEAR     -> The year the song was recorded.
#                NOT AVAILABLE FOR OGG FILES.
#
#   $GENRE    -> The genre of the track.
#                NOT AVAILABLE FOR OGG FILES.
#
#   $BPS      -> The sample rate of the song - if non-variable.
#                NOT AVAILABLE FOR OGG FILES.
#
#   $LENGTH   -> The length of the track in MM:SS
#                NOT AVALABLE FOR OGG FILES, OR VBR MP3's.
#
#   $SIZE     -> The size of the audio stream.
#                NOT AVAILABLE FOR OGG FILES, OR VBR MP3's.
#
#   $TRACK    -> The number of the track
#
#   $FILENAME will always be available.  (This is the name of the file
# without any suffix or directory information).
#
SONG_FORMAT = $ARTIST - $SONGNAME - $COMMENT - $FILENAME  [ $LENGTH / $SIZE ]



##
#
#  If you wish to change the text displayed on the 'Play'
# link you should uncomment the following option, and change the
# text appropriately.
#
##
#
play_recursively_text = Play all
##


##
#
#  This next option controls how songs are sorted prior to display,
# and used in the playlists.
#
#  You may use any of the $ values which are listed above in
# the 'song_format' setting, eg:
#
# Sort by track number if present.
# sort_order = $TRACK
#
# Sort by artist if present.
# sort_order = $ARTIST
##
sort_order = $SONGNAME





